### ISSUE TITLE
License of the Code and Styles

### ISSUE THREAD

**Issue by finnp** [victordarras/HeavyTable.js#2]
Hi :)

I really enjoy this plugin. I would love to use it in my own project, however I noticed  that there is no Open Source license. Could you maybe add one? Helpful for choosing a license is [this website](http://choosealicense.com/). I think MIT is generally quite nice.

Thanks,
Finn

**Comment by victordarras** [comment]
I added a license, use it wherever you want :)

**Comment by finnp** [comment]
Awesome thanks :+1:
